### ISSUE TITLE
Snap Store badge doesn't show up on the download page?

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes-foss-website#3]
The Snap Store badge doesn't show up on the download page? Can others verify if it's just on my end?

https://www.notes-foss.com/download

**Comment by guihkx** [comment]
Also not showing up here. I think this is snapcraft.io's fault:

![image](https://github.com/user-attachments/assets/eea2aad5-d34f-4124-a4c6-fb531b958c1c)

[Their `Cross-Origin-Resource-Policy` policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy#same-site) looks very restrictive right now:

```bash
$ curl -sI https://snapcraft.io/static/images/badges/en/snap-store-black.svg | grep -i 'cross-origin-resource-policy'
cross-origin-resource-policy: same-site
```
